global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ws-rest
    metrics_path: /prometheus
    static_configs:
      - targets:
          - host.docker.internal:80
  - job_name: picker
    metrics_path: /prometheus
    static_configs:
      - targets:
          - host.docker.internal:8012
