global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: ws-rest
    metrics_path: /prometheus
    static_configs:
      - targets:
          - eews-ws-rest:8080
  - job_name: picker
    metrics_path: /prometheus
    static_configs:
      - targets:
          - eews-picker-1:8012
          - eews-picker-2:8012
          - eews-picker-3:8012
  - job_name: queue
    metrics_path: /prometheus
    static_configs:
      - targets:
          - eews-queue-1:8012
          - eews-queue-2:8012
          - eews-queue-3:8012
  - job_name: producer
    metrics_path: /prometheus
    static_configs:
      - targets:
          - eews-producer:8082
